# Generated by Django 3.0.4 on 2020-03-27 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 3, 27, 6, 35, 33, 505162, tzinfo=utc))),
                ('content', models.TextField()),
            ],
        ),
    ]
