# Generated by Django 3.0.4 on 2020-03-27 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200327_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 9, 17, 22, 124373, tzinfo=utc)),
        ),
    ]
