# Generated by Django 3.0.4 on 2020-03-31 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200331_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 7, 8, 13, 782494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='heading',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 7, 8, 13, 783494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 7, 8, 13, 779490, tzinfo=utc)),
        ),
    ]
