# Generated by Django 3.0.4 on 2020-04-21 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200331_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 2, 8, 852696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='heading',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 2, 8, 854698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 2, 8, 848698, tzinfo=utc)),
        ),
    ]
