# Generated by Django 3.0.4 on 2020-04-21 14:13

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200421_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 13, 28, 202531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='heading',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 13, 28, 204532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
