# Generated by Django 3.0.4 on 2020-03-31 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200330_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 5, 9, 2, 598735, tzinfo=utc)),
        ),
    ]
