# Generated by Django 3.0.4 on 2020-04-21 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200331_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 2, 8, 909734, tzinfo=utc)),
        ),
    ]
