# Generated by Django 3.0.4 on 2020-04-21 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200421_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_data',
            new_name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
